spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-73-155-171.compute-1.amazonaws.com:5432/deld1maj6dmfp
    username: nbiytbfwowffis
    password: 90378041d02ad584facd7df21922e557e997368def70ff5eb65168bf858b9448

#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/online_excel
#    username: doston
#    password: doston123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  messages:
    always-use-message-format: true
  security:
    user:
      name: admin
      password: admin123

#service:
#  prop:
#    protocol: http
#    ip: localhost
#    port: 8080
#    url: boom.uz

service:
  prop:
    protocol: https
    ip:
    port:
    url: https://online-excel-heroku.herokuapp.com

api:
  info:
    title: Online Excel Swagger
    description: Swagger
    version: 1.0
    terms-of-service: https://unicorn.pdp.uz
    contact-name: pdp.uz
    contact-email: example@gmail.com
    contact-url: https://pdp.uz
    license-name: Apache 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html

springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api-docs