spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://ec2-54-160-109-68.compute-1.amazonaws.com:5432/db26hfv4nq7p77
#    username: bdnyqqmxgxvrnu
#    password: 79dedd3d3fa8976e89c4b112bbcff2ac5a320fb619ce4234cf8554996e6cb560

    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/online_excel
    username: doston
    password: doston123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  messages:
    always-use-message-format: true
  security:
    user:
      name: admin
      password: admin123

service:
  prop:
    protocol: http
    ip: localhost
    port: 8080
    url: boom.uz

api:
  info:
    title: Online Excel Swagger
    description: Swagger
    version: 1.0
    terms-of-service: https://unicorn.pdp.uz
    contact-name: pdp.uz
    contact-email: example@gmail.com
    contact-url: https://pdp.uz
    license-name: Apache 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html

springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api-docs